version: '3'
services:
  backend:
    build: .
    restart: always
    ports:
      - '5000:5000'
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    restart: always
    ports:
      - '3000:80'
